import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'antd/dist/reset.css';
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Content } from "antd/es/layout/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "News App",
  description: "Stay updated with the latest news and in-depth articles from around the world. Generated by create AliDSX",
  generator: 'Next.js',
  keywords: ['nextjs', 'pwa', 'news', 'articles'],
  icons: "/images/na.png",
  authors: [
    {
      name: "Ali Dhiaus Syamsi"
    }
  ],
  manifest: '/manifest.json',
  openGraph: {
    type: 'website',
    siteName: 'News App',
    title: 'News App',
    description: 'Stay updated with the latest news and in-depth articles from around the world.',
  },
  twitter: {
    card: 'summary',
    title: 'News App',
    description: 'Stay updated with the latest news and in-depth articles from around the world.',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Content style={{ maxWidth: 1200, margin: '0 auto', padding: '1rem' }}>
          {children}
        </Content>
        <Footer />
      </body>
    </html>
  );
}
